version: '3.9'

services:
  audiosync-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - database
    networks:
      - audiosync_network

  audiosync:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    networks:
      - audiosync_network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: se2_audiosync_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/prod:/docker-entrypoint-initdb.d
    networks:
      - audiosync_network

volumes:
  db_data:

networks:
  audiosync_network:
    driver: bridge