version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: database # Override the DB_HOST variable
      CORS_ORIGIN: http://frontend:3000
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: se2_audiosync_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/prod:/docker-entrypoint-initdb.d

volumes:
  db_data:
