version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    # Uncomment if using custom Docker network:
    # networks:
    #   - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Adjusted port mapping to match typical Nginx default port
    # Uncomment if using custom Docker network:
    # networks:
    #   - app-network

# Uncomment if using custom Docker network:
# networks:
#   app-network:
#     driver: bridge

