version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    networks:
      - audiosync-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map port 80 on the container to port 3000 on the host
    networks:
      - audiosync-net
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: se2_audiosync_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - audiosync-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - audiosync-net

volumes:
  db_data:


networks:
  audiosync-net: