name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Trigger only on pushes to the mian branch


jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: se2_audiosync_test_db
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MySQL to initialize
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot se2_audiosync_test_db < ./database/create_test_tables.sql
          mysql -h127.0.0.1 -uroot -proot se2_audiosync_test_db < ./database/seed_test_data.sql
          mysql -h127.0.0.1 -uroot -proot se2_audiosync_test_db < ./database/test_queries.sql

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: se2_audiosync_test_db
          DB_PORT: 3306
        run: npm test
