name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Trigger only on pushes to the mian branch


jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: se2_audiosync_db
        ports:
          - 3306:3306
    steps:
      - name: Wait for MySQL to initialize
        run: |
          until mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for database connection..."
            sleep 3
          done

  backend-tests:
    runs-on: ubuntu-latest
    needs: setup-db
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: se2_audiosync_test_db
          DB_PORT: 3306
        run: npm test
