name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Trigger only on pushes to the mian branch


jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.TEST_DB_NAME }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MySQL to initialize
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot ${{ secrets.TEST_DB_NAME }} < ./database/create_test_tables.sql
          mysql -h127.0.0.1 -uroot -proot ${{ secrets.TEST_DB_NAME }} < ./database/seed_test_data.sql
          mysql -h127.0.0.1 -uroot -proot ${{ secrets.TEST_DB_NAME }} < ./database/test_queries.sql

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_PORT: 3306
        run: npm test

  deployment:
    runs-on: ubuntu-latest
    needs: backend-tests  # Ensure deployment only happens if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}