name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: se2_audiosync_test_db
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MySQL to initialize
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot se2_audiosync_test_db < ./database/create_test_tables.sql
          mysql -h127.0.0.1 -uroot -proot se2_audiosync_test_db < ./database/seed_test_data.sql

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Set environment variables for tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_PORT: 3306
          NODE_ENV: test
          JWT_SECRET_KEY: fotis
          SESSION_SECRET: fotis
          SPOTIFY_CLIENT_ID: f63b8e82324843eeba6dc4af7f080138
          SPOTIFY_CLIENT_SECRET: 4e89beb1a54945449aaac0664499520e

        run: echo "Environment variables set for testing"

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_PORT: 3306
          NODE_ENV: test
        run: npm test

  deployment:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
